// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/watchlist/create": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create a new user with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CreateWatchlist"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateWatchlist"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/watchlist/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Handler function to fetch the user's watchlist data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetWatchlists"
                ],
                "summary": "Get the list of WatchLists",
                "responses": {
                    "200": {
                        "description": "Returns the user's watchlist data",
                        "schema": {
                            "$ref": "#/definitions/models.GetWatchlists"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/watchlist/scrips/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Retrieves the list of scrips for a given watchlist",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get Watchlist Scrips"
                ],
                "summary": "Get watchlist scrips",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the watchlist",
                        "name": "watchlist_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the user's watchlist's Scrips data",
                        "schema": {
                            "$ref": "#/definitions/models.GetWatchlistScrips"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateWatchlist": {
            "type": "object",
            "required": [
                "scrips",
                "watchlistName"
            ],
            "properties": {
                "scrips": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        44,
                        22
                    ]
                },
                "watchlistName": {
                    "type": "string",
                    "example": "Mid Watchlist"
                }
            }
        },
        "models.GetWatchlistScrips": {
            "type": "object",
            "properties": {
                "scrips": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Scrip"
                    }
                }
            }
        },
        "models.GetWatchlists": {
            "type": "object",
            "properties": {
                "watchlist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.Scrip": {
            "type": "object",
            "properties": {
                "symbol": {
                    "type": "string"
                },
                "token": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8081",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Stock Broker Application",
	Description:      "api for Stock Broker using gin and gorm",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
